### ISSUE TITLE
#1 エラー修正に関して on main-branch

### ISSUE THREAD

**Issue by nao317** [wotsu/KCLHack2024-PU-Back#4]
### As Is
- there is a bug on main-branch 
> ```go
> package crud
> 
> import (
>       
>         "KCL-Hack2024-PU-Back/database"
>
> )
> ```

### To Be
> ```go
> package crud
> 
> import (
>       
>         "KCLHack-PU-Back/database"
>
> )
> ```

なぜか、buridaikon/db-operateブランチで修正したエラーが修正されてないことに気づいた。ちなみに自分のローカルリポジトリはToBeになってるから、よくわからない。mainブランチだけ修正されてないから、慎重にいくべきだと思ってissue切らせてもらったよ。もう一回、自分のブランチ（buridaikon/db-operate）で修正しなおして、プッシュ→PRするのが安全かな？

**Comment by nao317** [comment]
ごめん
肝心なファイル名を書き忘れてた。
create_post.goのimportのところです。

**Comment by wotsu** [comment]
自分もよくわからんからとりあえずそうしてくれるとありがたい～
